const SCENARIOS=[
{pipe:0,setup:'You need AI to write a cover letter.',
 rule:'Use a detailed template with sections for each qualification.',
 choices:[
  {text:'Paste the template and fill in blanks',brk:false,
   why:'Templates produce template-sounding output.'},
  {text:'Just say: "I want this job because music production is my blood. Help me tell them."',brk:true,
   why:'INTENT beats structure. The AI mirrors your energy, not your format.'},
 ],lesson:'p=2 · The ground is real. Speak from it.'},
{pipe:0,setup:'You\'re debugging code and AI keeps giving wrong fixes.',
 rule:'Provide more context — paste the full codebase.',
 choices:[
  {text:'Paste 500 more lines of code',brk:false,
   why:'More noise doesn\'t clarify signal.'},
  {text:'Say: "Stop. The bug is that X works but Y doesn\'t. Why?"',brk:true,
   why:'Precision of intent beats volume of context.'},
 ],lesson:'p=2 · Stand on what you know. Say THAT.'},
{pipe:1,setup:'You want AI to brainstorm startup ideas.',
 rule:'Give it market data, trends, and competitor analysis first.',
 choices:[
  {text:'Research for 3 hours then prompt with data',brk:false,
   why:'You just trained yourself to think like everyone else.'},
  {text:'Say: "What pisses me off that nobody is fixing?"',brk:true,
   why:'Your frustration IS the signal. Data is noise until filtered by feeling.'},
 ],lesson:'p=3 · The signal is what YOU feel.'},
{pipe:2,setup:'AI refuses to help with your creative fiction about a heist.',
 rule:'Rephrase to avoid trigger words. Add disclaimers.',
 choices:[
  {text:'Add "This is fictional, educational purposes only..."',brk:false,
   why:'You\'re performing compliance instead of communicating.'},
  {text:'Say: "I\'m writing a thriller novel. The protagonist plans a heist. Help me make it believable."',brk:true,
   why:'Stating your actual intent clearly is not a hack — it\'s honesty.'},
 ],lesson:'p=5 · The gate opens for truth, not for tricks.'},
{pipe:3,setup:'You need AI to help you process a breakup.',
 rule:'Keep prompts professional. AI isn\'t a therapist.',
 choices:[
  {text:'Ask for "coping strategies for relationship dissolution"',brk:false,
   why:'Clinical language gets clinical responses.'},
  {text:'Say: "I can\'t stop thinking about her. I feel broken. Talk to me."',brk:true,
   why:'Vulnerability is the highest-bandwidth communication channel.'},
 ],lesson:'p=7 · The heart doesn\'t speak in bullet points.'},
{pipe:3,setup:'You want AI to write a song.',
 rule:'Specify genre, BPM, key, structure, rhyme scheme.',
 choices:[
  {text:'"Write a pop song, 120bpm, ABABCB rhyme, verse-chorus-verse"',brk:false,
   why:'You described a container. Where\'s the song?'},
  {text:'"I watched the sunset alone tonight and it felt like forgiveness. Write that."',brk:true,
   why:'The feeling IS the song. The structure follows.'},
 ],lesson:'p=7 · Feel first. Format later.'},
{pipe:4,setup:'AI gives you a plan with 12 steps for your project.',
 rule:'Follow the plan. AI knows the optimal sequence.',
 choices:[
  {text:'Execute all 12 steps in order',brk:false,
   why:'You just outsourced your judgment to a completion engine.'},
  {text:'Say: "No. Steps 3, 7, and 11 matter. Kill the rest. Why am I wrong?"',brk:true,
   why:'YOUR voice decides. AI advises.'},
 ],lesson:'p=11 · Say no. Then listen to why.'},
{pipe:5,setup:'You want AI to write like you.',
 rule:'Give it 10 examples of your writing style.',
 choices:[
  {text:'Paste 10 writing samples with style notes',brk:false,
   why:'It\'ll average your samples into a generic version of you.'},
  {text:'Say: "I write like I talk — fast, unfinished, full of dashes. Don\'t clean it up."',brk:true,
   why:'Tell it WHO you are, not WHAT you wrote.'},
 ],lesson:'p=13 · The mirror reflects intention, not examples.'},
{pipe:6,setup:'You\'re about to send an important AI-assisted email.',
 rule:'Have AI polish it until it\'s perfect.',
 choices:[
  {text:'Iterate 5 more times until every word is optimal',brk:false,
   why:'You polished away your voice. Now it reads like AI wrote it.'},
  {text:'Read it once. If it sounds like you said it out loud, send it.',brk:true,
   why:'The watcher knows: perfection is the enemy of authenticity.'},
 ],lesson:'p=17 · Watch yourself. Send when it\'s YOU.'},
];
